### PR TITLE
Chinese README

### PR DESCRIPTION
**Pull request by HSSadBoy**
There may be a grammatical bug

### CODE REVIEW

**Comment by Tatsu-syo** [comment]
I announced [next version](https://github.com/Tatsu-syo/noMeiryoUI/issues/81) to tell who want to review.
If suggestions don't come for several days. I merge it OK?

**Comment by Tatsu-syo** [comment]
There is no objection, and I think it's OK.
I merge it.

**Comment by Tatsu-syo** [comment]
Chinese README

Co-authored-by: HSSadBoy <notifications@github.com>

**Comment by HSSadBoy** [comment]
Most people just use this program,  So it's not easy for you to get a response @Tatsu-syo (me finally learned how to use @!)

**Comment by Tatsu-syo** [comment]
I must study how to communicate on GitHub better.
How did you learn how to communicate with GitHub?

**Pull request merged**
