### PR TITLE
Update zh-TW.lng

### PR DESCRIPTION
**Pull request by HSSadBoy**
正體中文

### CODE REVIEW

**Comment by Tatsu-syo** [comment]
Thank you for your cooperation.
I check your translation.
Messages about styles and Windows 11 22H2 warning are good.
But on Windows 11 22H2 section, space in section name, please remove.
Initially Windows 11 22H2 didn't applied.
And don't remove comments for later translators.
Thanks.

**Comment by HSSadBoy** [comment]
I'm So Sorry, But I want to know why SC does not have?

**Comment by Tatsu-syo** [comment]
> But I want to know why SC does not have?

Oh, somewhere I delete it by mistake.  
I'm planning to merge your two pull requests Simplified and Traditional Chinese, and reformat comments.  
How do you like it?

**Comment by HSSadBoy** [comment]
nice and accurate

**Comment by Tatsu-syo** [comment]
I Add comments in presets for another translators.
And remove spaces in Win 11 22H2 warning message.

**Pull request merged**
