### PR TITLE
Added Traditional Chinese (Taiwan) support

### PR DESCRIPTION
**Pull request by austin-chang**
Message file was translated from default. Help file was translated from English version.

### CODE REVIEW

**Comment by HSSadBoy** [comment]
（台繁不是Traditional Chinese吗）

**Comment by Tatsu-syo** [comment]
I changed Traditional Chinese(Taiwan) in English and Japanese help and credit.
Thanks.

**Comment by HSSadBoy** [comment]
> I changed Traditional Chinese(Taiwan) in English and Japanese helps and credits. Thanks.

Although I don't know u saying about,But I suspect you may not understand what I'm saying

What I really mean is "Chinese(Taiwan) should be
 Traditional Chinese(伝統的な中国語)

**Comment by HSSadBoy** [comment]
Your current Chinese Traditional is spoken in Taiwan, and I think we need to add a language, and now there are three mainstream languages in China:

Mainland use Simplified Chinese（简体中文）
Taiwan uses Traditional Chinese（正体中文）
Hong Kong and Macau Using Cantonese（繁体中文/粤语）

This is due to the fact that many Chinese characters are different in Taiwan and Hong Kong,  so it's best to have a distinction

**Comment by HSSadBoy** [comment]
> 

Or it could be like this
Simplified Chinese(China)
Traditional Chinese(Taiwan)
Traditional Chinese(Hong Kong)

 But I still suggest you use it
 Chinese Simplified
 Chinese Traditional
 Cantonese

This way it won't be confused with Chinese Traditional

**Comment by Tatsu-syo** [comment]
I use 
Simplified Chinese(China)
Traditional Chinese(Taiwan)
Traditional Chinese(Hong Kong)

Now Portuguese (Brazil) exists.Above style matches existed style.
And the style is similar to Windows style.
How about?

**Comment by HSSadBoy** [comment]
This is okay, most app are also like this

**Comment by Tatsu-syo** [comment]
Applied in help contents.
Thanks.

**Pull request merged**
