### PR TITLE
Improve grammar and follow GitHub's conventions on README

### PR DESCRIPTION
**Pull request by mon-jai**
I am still in the process of fine-tuning wordings and grammar. Do not merge yet.

### CODE REVIEW

**Comment by Tatsu-syo** [comment]
Thank you for your great work,
There is no problem.
I will merge it soon.

**Comment by mon-jai** [comment]
@Tatsu-syo Thanks for your comment. Why closing it?

**Comment by mon-jai** [comment]
If you plan to merge the changes in the future, remember to attribute me with git commit author field, or with [`Co-authored-by` trailer supported by GitHub](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors).

**Comment by Tatsu-syo** [comment]
I don't know right procedure to merge.
Reopen this issue.

**Comment by Tatsu-syo** [comment]
Futher work in after my public work, sory.

**Comment by Tatsu-syo** [comment]
@mon-jai 
I merge　git commit --amend and add Co-authored-by credits.
I am not familiar with Co-authored-by commits.
How about this way?
If you know better way, please tell me how to add Co-authored-by information.
Thank you and sorry.

**Comment by Tatsu-syo** [comment]
@mon-jai I merge via GitHub with Co-authored-by.
How about?

**Comment by mon-jai** [comment]
Yeah I saw it in the master branch.

Thanks for including my work.

**Comment by Tatsu-syo** [comment]
It was a good experience for me too.

Thank you for your contribution.

**Pull request merged**
