### PR TITLE
Update zh-CN.lng

### PR DESCRIPTION
**Pull request by kingofotaku**
Added missing warning text translations.

### CODE REVIEW

**Comment by Tatsu-syo** [comment]
Thank you for your cooperation.
I will include missing translations.
And another pull request is comming.
Defferents are below.What do you think?
----
DLG_CHARSET_DEFAULT=默认
DLG_CHARSET_HANGUL=朝鲜文
DLG_CHARSET_JOHAB=韩文(johab)

**Comment by kingofotaku** [comment]
I think it's OK.

**Comment by Tatsu-syo** [comment]
Another language uses Johab, so I use Johab.
And I use 朝鲜语.
Thank you for your advice.

**Comment by Tatsu-syo** [comment]
I use HSSadBoy's translations and after applying your suggestions.
So, I add you in Co-authored-by:
Thank you for your advices.

**Pull request closed without merging**
